spring.application.name=weather-forecast
server.port=8080

# Logging config
logging.level.root=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger : %msg%n
logging.file.name=logs/app.log

spring.cloud.config.enabled=false


# Cache settings (5-minute TTL)
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=300s

# OpenWeatherMap API Key
openweathermap.api.key=50bd24373c161c0a4fe873430a770e72
openweather.base.url=https://api.openweathermap.org/data/2.5